# Ask user to enter their name
print("What is your name?")
name = input()
print(f"It is nice to meet you {name}")


print("Please enter a character for the eye")
character = input()
print("The robots expression is now as follows:")
print("\n")
print("\n")
print("\n")
print("\t\t ##########")
print(f"\t\t # {character}    {character} #")
print("\t\t #        #")
print("\t\t #  ####  #")
print("\t\t ##########")
print("\t\t     #")
print("\t\t     #")
print("\t\t ##########      #")
print("\t\t ##########      #")
print("\t\t #################")
print("\t\t ##########")
print("\t\t     #")
print("\t\t     #")
print("\t\t     #")
print("\t\t   #######")
print("\t\t    #####")
print("\t\t    #   #")
print("\t\t   #    #")
print("\t\t  #     #")
print("\t\t #      #")
print("\t\t#       #")
print("\t   #        #")