# Ask user to enter their name
print("What is your name?")
name = input()
print(f"It is nice to meet you {name}")


print("Please enter a character for the eye")
character = input()
print("The robots expression is now as follows:")
print("\n")
print("\n")
print("\n")
print("\t\t ##########")
print(f"\t\t # {character}    {character} #")
print("\t\t #        #")
print("\t\t #  ####  #")
print("\t\t ##########")
print("\t\t     #")
print("\t\t     #")
print("\t\t ##########      #")
print("\t\t ##########      #")
print("\t\t #################")
print("\t\t ##########")
print("\t\t     #")
print("\t\t     #")
print("\t\t     #")
print("\t\t   #######")
print("\t\t    #####")
print("\t\t    #   #")
print("\t\t   #    #")
print("\t\t  #     #")
print("\t\t #      #")
print("\t\t#       #")
print("\t   #        #")

print("What is your name?")
name = input()
print("How old are you (in years)?")
age = input()
print("How tall are you (in meters)?")
height = input()
print("How much do you weigh (in kilograms)?")
weight = input()
print(f"{name} you are {age} years old and your bmi is {weight} / {height} **2}}")